### ISSUE TITLE
The 1.005 tag is not part of any branch

### ISSUE THREAD

**Issue by adelton** [book/Git-Version-Compare#3]
Hello @book,

the tag https://github.com/book/Git-Version-Compare/releases/tag/v1.005 points to commit https://github.com/book/Git-Version-Compare/commit/92a617d2d5c5aba839cdc7e5d51ce552d7e8d993 which says

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Indeed, there is only the `master` branch in the repository and the latest commit there is https://github.com/book/Git-Version-Compare/commit/5618c8a3d4496b40b04e9d80036845f1956e6917.

Assuming that 92a617d2d5c5aba839cdc7e5d51ce552d7e8d993 is some child commit to the current `master` HEAD, could you push it out to GitHub?

Thank you,

Jan

**Comment by book** [comment]
Thanks for the report. I've pushed `master` now.
